---
- hosts: all
  become: yes
  become_user: root
  become_method: sudo

  vars:
    helloworld: Hummming Bird!
    test-list: ['Template iterate','Template loop','Template item']

  tasks:
    - name: Install firewalld
      yum:
        name: firewalld

    - name: Stop firewalld
      service:
        name: firewalld
        state: stopped

    - name: Install the httpd package
      yum:
        name: httpd

    - name: Start the httpd service
      service:
        name: httpd
        state: started

    - name: Configure Cat App
      template:
        src: ../files/index.j2
        dest: /var/www/html/index.html

    - name: Loop example
      template:
        src: templates_example.j2
        dest: /var/www/html/loop.html
